stages:
  - build-test
  - test
  - deploy

docker-build-test:
  image: docker:latest
  stage: build-test
  service:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$TAG_IMAGE" -f DockerfileWmABE .
    - docker run
  rules:
    - if: $CI_COMMIT_BRANCH == "Devlopment"